# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1

    working_directory: ~/othdrplot

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          no_output_timeout: 10h
          command: |
            . venv/bin/activate
            export MPLBACKEND="Agg"
            coverage run -m pytest .
            coverage html
            mkdir test-reports
            mv htmlcov test-reports/coverage-report

      - store_artifacts:
          path: test-reports
          destination: test-reports
          